$axure.loadCurrentPage({
  "url":"头条页悬浮入口.html",
  "generationDate":new Date(1471945571045.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e48621edd7cc4170a72edaf6cfe00c7c",
    "type":"Axure:Page",
    "name":"头条页悬浮入口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c145c4de24d4868a7ce4768c1ed9f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e3bf05085124ca09f72468bcd45ddbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"45a564c0bb304e1c8c4822112479e658",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84e9862cd7e4e0ab6211be2fc4888a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"a04338175161434389766cb15d9598ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":109},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5ff63d0901b4662b355f7754c02227e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":109},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"bcf62b21f67d4904940abe93a02ba145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":148},
            "size":{
              "width":270,
              "height":111}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c1e014cb2144b4eaa924953cd21699b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":148},
                "size":{
                  "width":270,
                  "height":111}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u6.png"}},
{
          "id":"012f7341d0044544a0cc3db54287e3eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":258},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49a1ad07a9c04204826adf7d82dcd700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":258},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u8.png"}},
{
          "id":"cb9a18d98c5b4f4d9d504a0db1081f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":317},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e189769d82485393aeb4aefba67224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":317},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u8.png"}},
{
          "id":"90405e84be254b73b2fdb388594ff5d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":376},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e97c0288e1b445bacebeb8db0b9eff0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":376},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u8.png"}},
{
          "id":"055e3820e7b3427dbf137b991d655033",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":435},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b2a7b21ebc24f26a2422d8fc2cf42ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":435},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u8.png"}},
{
          "id":"47fe2923d74a4d47af67ee58d977d1e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":300,
              "y":445},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f5734f537e4ae2a4e26e991e7eb1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":300,
                  "y":445},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u16.png"}},
{
          "id":"e3a0eeb8ecd9455fb450422eee675427",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":460},
            "size":{
              "width":100,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/头条页悬浮入口/u18_line.png"}},
{
          "id":"549e5925269448ca802d698b6bc11155",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":457},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d74d2fdd13964a29ba1df6288527f5a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":457},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0880c31c7d243babbad6fc58ddbbd03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":85},
            "size":{
              "width":100,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/头条页悬浮入口/u18_line.png"}},
{
          "id":"3f7d88d4440a4fac8d4e6152c64a2a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":82},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95f66410a49146adb68d6f55e27d5385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":82},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cc2146c84ff4526bbefc64a819bafdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":80,
              "y":23},
            "size":{
              "width":141,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0da895ffce44900b69dfa39c89eff6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":80,
                  "y":23},
                "size":{
                  "width":141,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5c145c4de24d4868a7ce4768c1ed9f04":{
      "scriptId":"u0"},
    "5e3bf05085124ca09f72468bcd45ddbd":{
      "scriptId":"u1"},
    "45a564c0bb304e1c8c4822112479e658":{
      "scriptId":"u2"},
    "c84e9862cd7e4e0ab6211be2fc4888a9":{
      "scriptId":"u3"},
    "a04338175161434389766cb15d9598ed":{
      "scriptId":"u4"},
    "b5ff63d0901b4662b355f7754c02227e":{
      "scriptId":"u5"},
    "bcf62b21f67d4904940abe93a02ba145":{
      "scriptId":"u6"},
    "4c1e014cb2144b4eaa924953cd21699b":{
      "scriptId":"u7"},
    "012f7341d0044544a0cc3db54287e3eb":{
      "scriptId":"u8"},
    "49a1ad07a9c04204826adf7d82dcd700":{
      "scriptId":"u9"},
    "cb9a18d98c5b4f4d9d504a0db1081f89":{
      "scriptId":"u10"},
    "17e189769d82485393aeb4aefba67224":{
      "scriptId":"u11"},
    "90405e84be254b73b2fdb388594ff5d7":{
      "scriptId":"u12"},
    "6e97c0288e1b445bacebeb8db0b9eff0":{
      "scriptId":"u13"},
    "055e3820e7b3427dbf137b991d655033":{
      "scriptId":"u14"},
    "8b2a7b21ebc24f26a2422d8fc2cf42ec":{
      "scriptId":"u15"},
    "47fe2923d74a4d47af67ee58d977d1e7":{
      "scriptId":"u16"},
    "15f5734f537e4ae2a4e26e991e7eb1e1":{
      "scriptId":"u17"},
    "e3a0eeb8ecd9455fb450422eee675427":{
      "scriptId":"u18"},
    "549e5925269448ca802d698b6bc11155":{
      "scriptId":"u19"},
    "d74d2fdd13964a29ba1df6288527f5a5":{
      "scriptId":"u20"},
    "f0880c31c7d243babbad6fc58ddbbd03":{
      "scriptId":"u21"},
    "3f7d88d4440a4fac8d4e6152c64a2a51":{
      "scriptId":"u22"},
    "95f66410a49146adb68d6f55e27d5385":{
      "scriptId":"u23"},
    "7cc2146c84ff4526bbefc64a819bafdc":{
      "scriptId":"u24"},
    "e0da895ffce44900b69dfa39c89eff6e":{
      "scriptId":"u25"}}});