$axure.loadCurrentPage({
  "url":"我的-礼品、红包.html",
  "generationDate":new Date(1471945571418.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e60144ba8584e30b8822a002019e692",
    "type":"Axure:Page",
    "name":"我的-礼品、红包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0ac884c7ff944e50a452fa1cf6535603",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":67},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"352e50cb72ed45008d07e5c438b3cf75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":67},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"35e546a7623d47f8bf67c1a5375251cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":67},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e52bdb4cf9cb4fdf8d0ee6b04793efb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":67},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"997a29d5656a4911a967b46b90af89a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":217},
            "size":{
              "width":270,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f1c2c30d4d64bbead80cca21ba1f289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":217},
                "size":{
                  "width":270,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u4.png"}},
{
          "id":"f0f97a6a67984ed7a7fe1b662af36ab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":277},
            "size":{
              "width":270,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6b7e9cea5a4670b92d5bf7b463db91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":277},
                "size":{
                  "width":270,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u4.png"}},
{
          "id":"7c3a2e0c13a94783b17c66dc96e1042d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":575},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e84145ad4d43cb805cc35bcc9f1c95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":575},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"689b5156730b4df789bd4a46e0cb5b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":575},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a4b1a04e84e412597c85b67c154e729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":575},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"5f44b17f83e4425c808661348a78084a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":67},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d675c7ea7e14be68263da42ce3c3021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":67},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"e5426e5c05284d2c82d9201795c18d6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":67},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"494d4b843e734ea1b84498100c0876a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":67},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"3e4fbd2b79ad4a9bbb0bed364dd4ffe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":106},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e32585f7bdd44205a03b48b81a964059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":106},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"0e19ed0c6fc54ecea7871b53d2966a78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":156},
            "size":{
              "width":250,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff26420fdb124f6181de778b7ec2940f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":156},
                "size":{
                  "width":250,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u18.png"}},
{
          "id":"8352474439514a799966cda6e62008c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":222},
            "size":{
              "width":250,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的-礼品、红包/u20_line.png"}},
{
          "id":"8439060b935142a7af848a331f6999dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":164},
            "size":{
              "width":90,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"212a0709315a4519b9ddf3a698604ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":164},
                "size":{
                  "width":90,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u21.png"}},
{
          "id":"f6b24f1fb7214954b0276c478326ecaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":488,
              "y":235},
            "size":{
              "width":106,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d544f314ee8d49dfbd9c105c1b89d9b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":488,
                  "y":235},
                "size":{
                  "width":106,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c98b32f995db45bfbd76b16b3ce0fd86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":181},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f513f703198c480dbafa3002b31654d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":181},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1492fb696707470eb9449e9c956ae231",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":687,
              "y":233},
            "size":{
              "width":36,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e2e224401e4004a6ea36a53287e180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":687,
                  "y":233},
                "size":{
                  "width":36,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u27.png"}},
{
          "id":"dccd1885f05c4191a6864ac9f4e3f744",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":575},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae2727dc0da4e7684e9c07bc4b48cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":575},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"ed7167a4c8ce4951b423c05c4421b6f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":575},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"740be659b1da4b94a41d93dcbea0bf1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":575},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"403b4fb6d77547c7864136883d27a5d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":651},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d77576de754391bda4cebaba6886b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":651},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce3a51415b614c6da53a12ceda400356",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":684},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab66e875c7549fc8a60a081c2acd15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":684},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29ea3e66cfad404eaf72bf46a0bb4150",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":716},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38998d56c694f588aae823cca6e145e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":716},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f519742a0e5d4973964206d048026117",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":649},
            "size":{
              "width":164,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5209eb98a2ff424597f1678c422ad4a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":649},
                "size":{
                  "width":164,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u39.png"}},
{
          "id":"2ee5c852c10a4c68b475789b87b6f9b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":681},
            "size":{
              "width":164,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994a7fbfc72b47ab93e8cd50ba77e6b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":681},
                "size":{
                  "width":164,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u39.png"}},
{
          "id":"4b4a4d02fa1c4ac590f92bb9f5c46ba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":713},
            "size":{
              "width":164,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3251d5876d44f44b1ea7d5c14df05d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":713},
                "size":{
                  "width":164,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u39.png"}},
{
          "id":"e18c04ed8eb44eacb405cd30087ad646",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":470,
              "y":613},
            "size":{
              "width":270,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c0630f773dc45edb61697d10de7fd9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":470,
                  "y":613},
                "size":{
                  "width":270,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u45.png"}},
{
          "id":"510fe3326bf9410a9816c08bfdae0982",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":617},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b204ea6a8244684b697ad5e13a80eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":617},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d89d03e005a4d78b2e461cbf244ec6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":684,
              "y":617},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28f353f616e145a48035bf63d34aa1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":617},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6e383abd324897a80236e2bd88c8a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":484,
              "y":960},
            "size":{
              "width":242,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666961253b3b48bdbcec1f8e245b3a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":484,
                  "y":960},
                "size":{
                  "width":242,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u51.png"}},
{
          "id":"cb688d7e0cef43819a1da96048dc45b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":578,
              "y":765},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1724d2e222c645ac9d2914c426b722a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":578,
                  "y":765},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fcaedbeeb2b4857b1ac339a2e00fe6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":795},
            "size":{
              "width":250,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ebf64e046fc4ca099848175464d44b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":795},
                "size":{
                  "width":250,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5730a6544a984d3ea1b08011c3bdfd1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":67},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43d807784a9418a9d36c884d70b62ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":67},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"dcd635a939c24faf81bbd8eae839ca92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":67},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4578a3aab32b4a83b8370f7cc86175ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":67},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"93022bbf1a9e4b6681dfc7d7792a974e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":106},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa8087af2c9412c855a166fe0561b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":106},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"cb0a1c01a8554a9da468bf4e2126ba41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":156},
            "size":{
              "width":250,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25679e3ec78f47b8b28c7e2cd4ab5667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":156},
                "size":{
                  "width":250,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u18.png"}},
{
          "id":"d8a1bf256a3d4bdc8ae79fdeeacad7e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":222},
            "size":{
              "width":250,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的-礼品、红包/u20_line.png"}},
{
          "id":"0be03521ca6a4dd38554d08012e1bc08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":164},
            "size":{
              "width":90,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61478ec6978f498aae559d197aace4f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":164},
                "size":{
                  "width":90,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u21.png"}},
{
          "id":"088fb2f860c74662ba7169af74016ec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1023,
              "y":165},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aae7d9c3f2dd4f9a982ca7ea4fc75d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1023,
                  "y":165},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edcc21b391de453b903847c6434e2a8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1023,
              "y":186},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4dcd6b52c404299b3031ddbe5956132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1023,
                  "y":186},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85d74e5e1f4347cea2b568d674ff1652",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":267},
            "size":{
              "width":250,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ab2561fd4b4709be0b34595c637658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":267},
                "size":{
                  "width":250,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u18.png"}},
{
          "id":"e8d63fc6ae66404fa367a87c2f84d5b3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":333},
            "size":{
              "width":250,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的-礼品、红包/u20_line.png"}},
{
          "id":"bbe17c17a0304b06a3ba490e5ed2caf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":275},
            "size":{
              "width":90,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b915a3843343edaedad945c4c18158",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":275},
                "size":{
                  "width":90,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u21.png"}},
{
          "id":"8ebcd92b9fef4637b352ec995d8307c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1023,
              "y":276},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c25acaf0838464783603913bd263f83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1023,
                  "y":276},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf6d9c06710f487f910cd0d3a2c113b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1023,
              "y":297},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c45d2c0874d4ef7899c9d2a246b3c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1023,
                  "y":297},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07c09e18061b45ddb9079677cb87387a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":920,
              "y":235},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b108aa5ff1b041e8b51f8ced45773b2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":920,
                  "y":235},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"505c676d13cc417295bf418c04867864",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":920,
              "y":346},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fbeaff3c0c441989f070d322890c02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":920,
                  "y":346},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f1689ee1bcb46eca3c643e63691062b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":1090,
              "y":346},
            "size":{
              "width":63,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b09c81f8b540f4a8e7067f8ea07a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":1090,
                  "y":346},
                "size":{
                  "width":63,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f47dd60cd9ab485784405cb893278a02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1330,
              "y":67},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98fc474de9224189a5dcd43195d3fc21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1330,
                  "y":67},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"8393dea7a8ab489dbd8a412404714fb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1330,
              "y":67},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4052f9a059b94111a7e430d844652a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1330,
                  "y":67},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"6ea350dd56034953b2fe724110e1c49e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1330,
              "y":106},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aae5eedb34d4f8695755d5c56ef6b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1330,
                  "y":106},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u2.png"}},
{
          "id":"5eddc7b1804b45e5b5694a34bf933726",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1340,
              "y":156},
            "size":{
              "width":250,
              "height":100},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc2175d10a284fd7a0cbded04ed6c375",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1340,
                  "y":156},
                "size":{
                  "width":250,
                  "height":100},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u18.png"}},
{
          "id":"f2f4de5ee8034194b1fe37cd4bbc8903",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1340,
              "y":222},
            "size":{
              "width":250,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的-礼品、红包/u20_line.png"}},
{
          "id":"0c188e77def84448b30c3bfe27ae1bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":164},
            "size":{
              "width":90,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80606cf7f34d444398127740d1eccb7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":164},
                "size":{
                  "width":90,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u21.png"}},
{
          "id":"047ce80340904b6e9a3907aed407a015",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1450,
              "y":185},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c0a6b0e14c74592a0d4702e1ea290a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1450,
                  "y":185},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a856a732a1e45b0934097d42c13b165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":1350,
              "y":235},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efac8ed1024b4dad97e3ffa2fac9816f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":1350,
                  "y":235},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58faf118fcde4b3d8bf2ecb4f8ebb8e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":1090,
              "y":235},
            "size":{
              "width":63,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ed54ac1774431fb817be4601bb0af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":1090,
                  "y":235},
                "size":{
                  "width":63,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9dc47031bda46cea1f83411d1c5b8b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":60,
              "y":24},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce553eb89b624fa9b16ae9b303472c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":60,
                  "y":24},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b6a4c15104946c388eb7abf743bc19d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":60,
              "y":530},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad77954035c450fbfe8c84514a5a731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":60,
                  "y":530},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9da7ac3a5fd543718fec2d2be8a5a144",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":470,
              "y":24},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9936f27d358e4371be73f680ddcd1e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":470,
                  "y":24},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"839472062a984c7baf4ba31980583a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":900,
              "y":24},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a57ebf9795e4dde9882d66c5f850d45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":900,
                  "y":24},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00325c9065404fb3a0e32e09a6c030bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1330,
              "y":24},
            "size":{
              "width":148,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c9201689a74d74ac314dfeb5cf6082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":1330,
                  "y":24},
                "size":{
                  "width":148,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55a1910f56fb4f8d8dbb515079d8799d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":734,
              "y":681},
            "size":{
              "width":120,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的-礼品、红包/u114_line.png"}},
{
          "id":"d64cc562d64144d6b4e33dba4834dd5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":864,
              "y":681},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84fc14167b9c401b8a538df995661afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":864,
                  "y":681},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6de0bf309b6b4a6589abb38233331f65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":625},
            "size":{
              "width":250,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033b0864478846debde829d77bc544b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":625},
                "size":{
                  "width":250,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e3ee3f252a44759cc0b819c08064c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":270,
              "height":425}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4b9464c93240f78c9be6bc6817070b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":270,
                  "height":425}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/头条页悬浮入口/u0.png"}},
{
          "id":"3c981eeffefc445ab851ccb882cb800b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1090},
            "size":{
              "width":270,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b4461fc4f354449b76afbfa0bbb7d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1090},
                "size":{
                  "width":270,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u121.png"}},
{
          "id":"ea719bf1b5454b90ba7b387c40aa7188",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1205},
            "size":{
              "width":230,
              "height":101},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0a46021db734e0ab3028139a4ac48f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":1205},
                "size":{
                  "width":230,
                  "height":101},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的-礼品、红包/u123.png"}},
{
          "id":"a7455b1cb206433083e5a563c48a2ea5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":92,
              "y":1230},
            "size":{
              "width":207,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"546ebeb54c7e4abb99d6741dd8ecede1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":92,
                  "y":1230},
                "size":{
                  "width":207,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f90b6e95be72416880946b9479871c75",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":1274},
            "size":{
              "width":60,
              "height":18}},
          "adaptiveStyles":{
}},
{
          "id":"f896de1734bd49bea26382fa8f2f9173",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":1274},
            "size":{
              "width":60,
              "height":18}},
          "adaptiveStyles":{
}},
{
          "id":"1e212456e90a4bd591b745ad11ae2003",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":60,
              "y":1040},
            "size":{
              "width":261,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d080c1c3a3754419aff5339c2da65e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":60,
                  "y":1040},
                "size":{
                  "width":261,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2210aaacbdcb489b9b0885bb17c32f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":470,
              "y":530},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14415458737f47359780aebfc769bb34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":470,
                  "y":530},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0ac884c7ff944e50a452fa1cf6535603":{
      "scriptId":"u0"},
    "352e50cb72ed45008d07e5c438b3cf75":{
      "scriptId":"u1"},
    "35e546a7623d47f8bf67c1a5375251cc":{
      "scriptId":"u2"},
    "e52bdb4cf9cb4fdf8d0ee6b04793efb6":{
      "scriptId":"u3"},
    "997a29d5656a4911a967b46b90af89a7":{
      "scriptId":"u4"},
    "3f1c2c30d4d64bbead80cca21ba1f289":{
      "scriptId":"u5"},
    "f0f97a6a67984ed7a7fe1b662af36ab4":{
      "scriptId":"u6"},
    "9d6b7e9cea5a4670b92d5bf7b463db91":{
      "scriptId":"u7"},
    "7c3a2e0c13a94783b17c66dc96e1042d":{
      "scriptId":"u8"},
    "31e84145ad4d43cb805cc35bcc9f1c95":{
      "scriptId":"u9"},
    "689b5156730b4df789bd4a46e0cb5b4b":{
      "scriptId":"u10"},
    "6a4b1a04e84e412597c85b67c154e729":{
      "scriptId":"u11"},
    "5f44b17f83e4425c808661348a78084a":{
      "scriptId":"u12"},
    "1d675c7ea7e14be68263da42ce3c3021":{
      "scriptId":"u13"},
    "e5426e5c05284d2c82d9201795c18d6b":{
      "scriptId":"u14"},
    "494d4b843e734ea1b84498100c0876a8":{
      "scriptId":"u15"},
    "3e4fbd2b79ad4a9bbb0bed364dd4ffe6":{
      "scriptId":"u16"},
    "e32585f7bdd44205a03b48b81a964059":{
      "scriptId":"u17"},
    "0e19ed0c6fc54ecea7871b53d2966a78":{
      "scriptId":"u18"},
    "ff26420fdb124f6181de778b7ec2940f":{
      "scriptId":"u19"},
    "8352474439514a799966cda6e62008c1":{
      "scriptId":"u20"},
    "8439060b935142a7af848a331f6999dd":{
      "scriptId":"u21"},
    "212a0709315a4519b9ddf3a698604ace":{
      "scriptId":"u22"},
    "f6b24f1fb7214954b0276c478326ecaa":{
      "scriptId":"u23"},
    "d544f314ee8d49dfbd9c105c1b89d9b5":{
      "scriptId":"u24"},
    "c98b32f995db45bfbd76b16b3ce0fd86":{
      "scriptId":"u25"},
    "f513f703198c480dbafa3002b31654d7":{
      "scriptId":"u26"},
    "1492fb696707470eb9449e9c956ae231":{
      "scriptId":"u27"},
    "67e2e224401e4004a6ea36a53287e180":{
      "scriptId":"u28"},
    "dccd1885f05c4191a6864ac9f4e3f744":{
      "scriptId":"u29"},
    "eae2727dc0da4e7684e9c07bc4b48cb2":{
      "scriptId":"u30"},
    "ed7167a4c8ce4951b423c05c4421b6f5":{
      "scriptId":"u31"},
    "740be659b1da4b94a41d93dcbea0bf1c":{
      "scriptId":"u32"},
    "403b4fb6d77547c7864136883d27a5d3":{
      "scriptId":"u33"},
    "17d77576de754391bda4cebaba6886b4":{
      "scriptId":"u34"},
    "ce3a51415b614c6da53a12ceda400356":{
      "scriptId":"u35"},
    "5ab66e875c7549fc8a60a081c2acd15d":{
      "scriptId":"u36"},
    "29ea3e66cfad404eaf72bf46a0bb4150":{
      "scriptId":"u37"},
    "b38998d56c694f588aae823cca6e145e":{
      "scriptId":"u38"},
    "f519742a0e5d4973964206d048026117":{
      "scriptId":"u39"},
    "5209eb98a2ff424597f1678c422ad4a8":{
      "scriptId":"u40"},
    "2ee5c852c10a4c68b475789b87b6f9b4":{
      "scriptId":"u41"},
    "994a7fbfc72b47ab93e8cd50ba77e6b1":{
      "scriptId":"u42"},
    "4b4a4d02fa1c4ac590f92bb9f5c46ba2":{
      "scriptId":"u43"},
    "d3251d5876d44f44b1ea7d5c14df05d4":{
      "scriptId":"u44"},
    "e18c04ed8eb44eacb405cd30087ad646":{
      "scriptId":"u45"},
    "6c0630f773dc45edb61697d10de7fd9a":{
      "scriptId":"u46"},
    "510fe3326bf9410a9816c08bfdae0982":{
      "scriptId":"u47"},
    "1b204ea6a8244684b697ad5e13a80eff":{
      "scriptId":"u48"},
    "0d89d03e005a4d78b2e461cbf244ec6b":{
      "scriptId":"u49"},
    "28f353f616e145a48035bf63d34aa1b4":{
      "scriptId":"u50"},
    "0b6e383abd324897a80236e2bd88c8a2":{
      "scriptId":"u51"},
    "666961253b3b48bdbcec1f8e245b3a18":{
      "scriptId":"u52"},
    "cb688d7e0cef43819a1da96048dc45b9":{
      "scriptId":"u53"},
    "1724d2e222c645ac9d2914c426b722a4":{
      "scriptId":"u54"},
    "4fcaedbeeb2b4857b1ac339a2e00fe6b":{
      "scriptId":"u55"},
    "1ebf64e046fc4ca099848175464d44b7":{
      "scriptId":"u56"},
    "5730a6544a984d3ea1b08011c3bdfd1b":{
      "scriptId":"u57"},
    "c43d807784a9418a9d36c884d70b62ec":{
      "scriptId":"u58"},
    "dcd635a939c24faf81bbd8eae839ca92":{
      "scriptId":"u59"},
    "4578a3aab32b4a83b8370f7cc86175ac":{
      "scriptId":"u60"},
    "93022bbf1a9e4b6681dfc7d7792a974e":{
      "scriptId":"u61"},
    "afa8087af2c9412c855a166fe0561b78":{
      "scriptId":"u62"},
    "cb0a1c01a8554a9da468bf4e2126ba41":{
      "scriptId":"u63"},
    "25679e3ec78f47b8b28c7e2cd4ab5667":{
      "scriptId":"u64"},
    "d8a1bf256a3d4bdc8ae79fdeeacad7e4":{
      "scriptId":"u65"},
    "0be03521ca6a4dd38554d08012e1bc08":{
      "scriptId":"u66"},
    "61478ec6978f498aae559d197aace4f6":{
      "scriptId":"u67"},
    "088fb2f860c74662ba7169af74016ec2":{
      "scriptId":"u68"},
    "aae7d9c3f2dd4f9a982ca7ea4fc75d84":{
      "scriptId":"u69"},
    "edcc21b391de453b903847c6434e2a8a":{
      "scriptId":"u70"},
    "e4dcd6b52c404299b3031ddbe5956132":{
      "scriptId":"u71"},
    "85d74e5e1f4347cea2b568d674ff1652":{
      "scriptId":"u72"},
    "18ab2561fd4b4709be0b34595c637658":{
      "scriptId":"u73"},
    "e8d63fc6ae66404fa367a87c2f84d5b3":{
      "scriptId":"u74"},
    "bbe17c17a0304b06a3ba490e5ed2caf2":{
      "scriptId":"u75"},
    "41b915a3843343edaedad945c4c18158":{
      "scriptId":"u76"},
    "8ebcd92b9fef4637b352ec995d8307c0":{
      "scriptId":"u77"},
    "2c25acaf0838464783603913bd263f83":{
      "scriptId":"u78"},
    "bf6d9c06710f487f910cd0d3a2c113b8":{
      "scriptId":"u79"},
    "6c45d2c0874d4ef7899c9d2a246b3c04":{
      "scriptId":"u80"},
    "07c09e18061b45ddb9079677cb87387a":{
      "scriptId":"u81"},
    "b108aa5ff1b041e8b51f8ced45773b2e":{
      "scriptId":"u82"},
    "505c676d13cc417295bf418c04867864":{
      "scriptId":"u83"},
    "03fbeaff3c0c441989f070d322890c02":{
      "scriptId":"u84"},
    "6f1689ee1bcb46eca3c643e63691062b":{
      "scriptId":"u85"},
    "b2b09c81f8b540f4a8e7067f8ea07a9b":{
      "scriptId":"u86"},
    "f47dd60cd9ab485784405cb893278a02":{
      "scriptId":"u87"},
    "98fc474de9224189a5dcd43195d3fc21":{
      "scriptId":"u88"},
    "8393dea7a8ab489dbd8a412404714fb9":{
      "scriptId":"u89"},
    "4052f9a059b94111a7e430d844652a8e":{
      "scriptId":"u90"},
    "6ea350dd56034953b2fe724110e1c49e":{
      "scriptId":"u91"},
    "0aae5eedb34d4f8695755d5c56ef6b3f":{
      "scriptId":"u92"},
    "5eddc7b1804b45e5b5694a34bf933726":{
      "scriptId":"u93"},
    "fc2175d10a284fd7a0cbded04ed6c375":{
      "scriptId":"u94"},
    "f2f4de5ee8034194b1fe37cd4bbc8903":{
      "scriptId":"u95"},
    "0c188e77def84448b30c3bfe27ae1bfd":{
      "scriptId":"u96"},
    "80606cf7f34d444398127740d1eccb7c":{
      "scriptId":"u97"},
    "047ce80340904b6e9a3907aed407a015":{
      "scriptId":"u98"},
    "1c0a6b0e14c74592a0d4702e1ea290a7":{
      "scriptId":"u99"},
    "2a856a732a1e45b0934097d42c13b165":{
      "scriptId":"u100"},
    "efac8ed1024b4dad97e3ffa2fac9816f":{
      "scriptId":"u101"},
    "58faf118fcde4b3d8bf2ecb4f8ebb8e7":{
      "scriptId":"u102"},
    "81ed54ac1774431fb817be4601bb0af4":{
      "scriptId":"u103"},
    "f9dc47031bda46cea1f83411d1c5b8b1":{
      "scriptId":"u104"},
    "ce553eb89b624fa9b16ae9b303472c9d":{
      "scriptId":"u105"},
    "5b6a4c15104946c388eb7abf743bc19d":{
      "scriptId":"u106"},
    "cad77954035c450fbfe8c84514a5a731":{
      "scriptId":"u107"},
    "9da7ac3a5fd543718fec2d2be8a5a144":{
      "scriptId":"u108"},
    "9936f27d358e4371be73f680ddcd1e33":{
      "scriptId":"u109"},
    "839472062a984c7baf4ba31980583a7f":{
      "scriptId":"u110"},
    "9a57ebf9795e4dde9882d66c5f850d45":{
      "scriptId":"u111"},
    "00325c9065404fb3a0e32e09a6c030bc":{
      "scriptId":"u112"},
    "f9c9201689a74d74ac314dfeb5cf6082":{
      "scriptId":"u113"},
    "55a1910f56fb4f8d8dbb515079d8799d":{
      "scriptId":"u114"},
    "d64cc562d64144d6b4e33dba4834dd5e":{
      "scriptId":"u115"},
    "84fc14167b9c401b8a538df995661afd":{
      "scriptId":"u116"},
    "6de0bf309b6b4a6589abb38233331f65":{
      "scriptId":"u117"},
    "033b0864478846debde829d77bc544b2":{
      "scriptId":"u118"},
    "c3e3ee3f252a44759cc0b819c08064c8":{
      "scriptId":"u119"},
    "4c4b9464c93240f78c9be6bc6817070b":{
      "scriptId":"u120"},
    "3c981eeffefc445ab851ccb882cb800b":{
      "scriptId":"u121"},
    "2b4461fc4f354449b76afbfa0bbb7d98":{
      "scriptId":"u122"},
    "ea719bf1b5454b90ba7b387c40aa7188":{
      "scriptId":"u123"},
    "c0a46021db734e0ab3028139a4ac48f4":{
      "scriptId":"u124"},
    "a7455b1cb206433083e5a563c48a2ea5":{
      "scriptId":"u125"},
    "546ebeb54c7e4abb99d6741dd8ecede1":{
      "scriptId":"u126"},
    "f90b6e95be72416880946b9479871c75":{
      "scriptId":"u127"},
    "f896de1734bd49bea26382fa8f2f9173":{
      "scriptId":"u128"},
    "1e212456e90a4bd591b745ad11ae2003":{
      "scriptId":"u129"},
    "d080c1c3a3754419aff5339c2da65e76":{
      "scriptId":"u130"},
    "2210aaacbdcb489b9b0885bb17c32f64":{
      "scriptId":"u131"},
    "14415458737f47359780aebfc769bb34":{
      "scriptId":"u132"}}});